In [1]:
import json
import os
from torch.utils.data.dataset import random_split
import csv

In [19]:
import random
random.seed(26)

In [20]:
##将反向关系加入负例中  在1:2基础上
with open('../data/train_data.json','rt',encoding='utf-8') as fin1,open('../data/test_data.json','rt',encoding='utf-8') as fin2,\
open('../data/train_new.json','w',newline='',encoding='utf-8') as fout1,open('../data/test_new.json','w',newline='',encoding='utf-8') as fout2:
    train_=[]
    for line in fin1:
        line = line.strip()
        if not line:
            continue  #结束则跳出循环
        sentence = json.loads(line)#将json数据转换成python对象  这里是转换为了字典
        train_.append(sentence)

    for tr in train_:
        sentence_text=list(tr["sentText"].strip().strip('"'))
#         print(len(sentence_text))
        entity_list=[]
        entitypair_list=[]
        entity_list_other=[]
        entitypair_list_other=[]
        for entity in tr["entityMentions"]:
            entity_list_other.append((entity['text'],entity['start']))
            if entity['label']=='Nh' or entity['label']=='NDR':
                
                entity_list.append((entity['text'],entity['start']))
            
            
                
#             entity_list.append((entity['text'],entity['start']))
        for e1 in entity_list_other:
            for e2 in entity_list_other:
                if e1!=e2:
                    entitypair=set()
                    entitypair.add(e1)
                    entitypair.add(e2)
                    if entitypair not in entitypair_list_other:
                        entitypair_list_other.append(entitypair)
#         print(len(entitypair_list))
        for e1 in entity_list:
            for e2 in entity_list:
                if e1!=e2:
                    entitypair=set()
                    entitypair.add(e1)
                    entitypair.add(e2)
                    if entitypair not in entitypair_list:
                        entitypair_list.append(entitypair)
                        
        for relation in tr['relationMentions']:
            if relation['label']!='NA':
                sent=sentence_text.copy()

                e1=relation['em1Text']
                e2=relation['em2Text']
                re=relation['label']

                re_pair=set()
                re_pair.add(e1)
                re_pair.add(e2)
                
                if re_pair in entitypair_list:
                    entitypair_list.remove(re_pair)
                
                tr['relationMentions'].append({"e1start":relation['e21start'],\
                                               "em1Text":relation['em2Text'],\
                                               "e21start":relation['e1start'],\
                                               "em2Text":relation['em1Text'],\
                                               "label":'NA'})
#             wtrain.writerow((e1,e2,re,''.join(sent)))
            #print(sid,''.join(sent),re_type,sentID)
    
#             print(sentence_text[j],label[j])
#             if re not in relation_list:
#                 relation_list.append(re)
#         print(len(entitypair_list))
#         if len(entitypair_list_other)>2:
        
#             ranlist=random.sample(entitypair_list_other,2)
#             for ran in ranlist:
#                 tr['relationMentions'].append({"e1start":list(ran)[0][1],\
#                                                "em1Text":list(ran)[0][0],\
#                                                "e21start":list(ran)[1][1],\
#                                                "em2Text":list(ran)[1][0],\
#                                                "label":'NA'})
        if len(entitypair_list)>5:
            ranlist=entitypair_list
            ranlist=random.sample(entitypair_list,5)
            for ran in ranlist:
                tr['relationMentions'].append({"e1start":list(ran)[0][1],\
                                               "em1Text":list(ran)[0][0],\
                                               "e21start":list(ran)[1][1],\
                                               "em2Text":list(ran)[1][0],\
                                               "label":'NA'})
#         else:
#             for ran in entitypair_list:
#                 tr['relationMentions'].append({"e1start":list(ran)[0][1],\
#                                                "em1Text":list(ran)[0][0],\
#                                                "e21start":list(ran)[1][1],\
#                                                "em2Text":list(ran)[1][0],\
#                                                "label":'NA'})

        fout1.write(json.dumps(tr,ensure_ascii=False)+'\n')
      
    
 
    test_=[]
    for line in fin2:
        line = line.strip()
        if not line:
            continue  #结束则跳出循环
        sentence = json.loads(line)#将json数据转换成python对象  这里是转换为了字典
        test_.append(sentence)
    
    for te in test_:
        sentence_text=list(te["sentText"].strip().strip('"'))
#         print(len(sentence_text))
        entity_list=[]
        entitypair_list=[]
        
        for entity in te["entityMentions"]:
            
            if entity['label']=='Nh' or entity['label']=='NDR':
                
                entity_list.append((entity['text'],entity['start']))
           
#             entity_list.append((entity['text'],entity['start']))
        for e1 in entity_list:
            for e2 in entity_list:
                if e1!=e2:
                    entitypair=set()
                    entitypair.add(e1)
                    entitypair.add(e2)
                    if entitypair not in entitypair_list:
                        entitypair_list.append(entitypair)
                       
        for relation in te['relationMentions']:
            if relation['label']!='NA':
                sent=sentence_text.copy()

                e1=relation['em1Text']
                e2=relation['em2Text']
                re=relation['label']

                re_pair=set()
                re_pair.add(e1)
                re_pair.add(e2)

                if re_pair in entitypair_list:
                    entitypair_list.remove(re_pair)
                te['relationMentions'].append({"e1start":relation['e21start'],\
                                               "em1Text":relation['em2Text'],\
                                               "e21start":relation['e1start'],\
                                               "em2Text":relation['em1Text'],\
                                               "label":'NA'})
#         print(1,len(te['relationMentions']))
        if len(entitypair_list)>5:
            ranlist=entitypair_list
            ranlist=random.sample(entitypair_list,5)
            
            for ran in ranlist:
                te['relationMentions'].append({"e1start":list(ran)[0][1],\
                                               "em1Text":list(ran)[0][0],\
                                               "e21start":list(ran)[1][1],\
                                               "em2Text":list(ran)[1][0],\
                                               "label":'NA'})

#         else:
#             for ran in entitypair_list:
#                 tr['relationMentions'].append({"e1start":list(ran)[0][1],\
#                                                "em1Text":list(ran)[0][0],\
#                                                "e21start":list(ran)[1][1],\
#                                                "em2Text":list(ran)[1][0],\
#                                                "label":'NA'})
#         print(len(te['relationMentions']))
        fout2.write(json.dumps(te,ensure_ascii=False)+'\n')

In [21]:
with open('../data/train_new.json','rt',encoding='utf-8') as fin1,open('../data/test_new.json','rt',encoding='utf-8') as fin2,\
open('../data/train.tsv','w',newline='',encoding='utf-8') as fout1,open('../data/dev.tsv','w',newline='',encoding='utf-8') as fout2,open('../data/test.tsv','w',newline='',encoding='utf-8') as fout3:
    wtrain=csv.writer(fout1,delimiter='\t')
    wvalid=csv.writer(fout2,delimiter='\t')
    wtest=csv.writer(fout3,delimiter='\t')
    sid=0
    train_=[]
    for line in fin1:
        line = line.strip()
        if not line:
            continue  #结束则跳出循环
        sentence = json.loads(line)#将json数据转换成python对象  这里是转换为了字典
        train_.append(sentence)
    train_size=len(train_)
    val_size = int(0.25 * len(train_))
    train_,val_= random_split(train_, [train_size-val_size,val_size])
    train_=list(train_)
    val_=list(val_)
    
    
    fre=open('relations.txt','r',encoding='utf-8') 
    relation_type=[x.strip() for x in fre.readlines()]
    
    print(relation_type)
    
    for tr in train_:
        sentence_text=list(tr["sentText"].strip().strip('"'))
#         print(len(sentence_text))
        sentID=str(tr['articleId'])+'-'+str(tr['sentId'])
        #print(tr)
            
        for relation in tr['relationMentions']:
            sent=sentence_text.copy()
            
            e1start=relation['e1start']
            e1end=e1start+len(relation['em1Text'])
            e2start=relation['e21start']
            e2end=e2start+len(relation['em2Text'])
            re_type=relation_type.index(relation['label'])
            
            if e1end>400 or e2end>400:
                continue
                
            if e1start<e2start:
                sent.insert(e2end,'[E22]')
                sent.insert(e2start,'[E21]')
                sent.insert(e1end,'[E12]')
                sent.insert(e1start,'[E11]')
            else:
                sent.insert(e1end,'[E12]')
                sent.insert(e1start,'[E11]')
                sent.insert(e2end,'[E22]')
                sent.insert(e2start,'[E21]')
                
            wtrain.writerow((sid,''.join(sent),re_type,sentID))
            #print(sid,''.join(sent),re_type,sentID)
            sid+=1
#             print(sentence_text[j],label[j])
    sid=0
    for vl in val_:
        sentence_text=list(vl["sentText"].strip().strip('"'))
#         print(len(sentence_text))
        sentID=str(vl['articleId'])+'-'+str(vl['sentId'])
        #print(tr)
        for relation in vl['relationMentions']:
            sent=sentence_text.copy()
            
            e1start=relation['e1start']
            e1end=e1start+len(relation['em1Text'])
            e2start=relation['e21start']
            e2end=e2start+len(relation['em2Text'])
            re_type=relation_type.index(relation['label'])
            
            if e1end>400 or e2end>400:
                continue
                
            if e1start<e2start:
                sent.insert(e2end,'[E22]')
                sent.insert(e2start,'[E21]')
                sent.insert(e1end,'[E12]')
                sent.insert(e1start,'[E11]')
            else:
                sent.insert(e1end,'[E12]')
                sent.insert(e1start,'[E11]')
                sent.insert(e2end,'[E22]')
                sent.insert(e2start,'[E21]')
                
            wvalid.writerow((sid,''.join(sent),re_type,sentID))
            #print(sid,''.join(sent),re_type,sentID)
            sid+=1
#             print(sentence_text[j],label[j])
    
    sid=0
    test_=[]
    for line in fin2:
        line = line.strip()
        if not line:
            continue  #结束则跳出循环
        sentence = json.loads(line)#将json数据转换成python对象  这里是转换为了字典
        test_.append(sentence)
    
    for te in test_:
        sentence_text=list(te["sentText"].strip().strip('"'))
#         print(len(sentence_text))
        sentID=str(te['articleId'])+'-'+str(te['sentId'])
        #print(tr)
        for relation in te['relationMentions']:
            sent=sentence_text.copy()
            
            e1start=relation['e1start']
            e1end=e1start+len(relation['em1Text'])
            e2start=relation['e21start']
            e2end=e2start+len(relation['em2Text'])
            re_type=relation_type.index(relation['label'])
            
            if e1end>400 or e2end>400:
                continue
                
            if e1start<e2start:
                sent.insert(e2end,'[E22]')
                sent.insert(e2start,'[E21]')
                sent.insert(e1end,'[E12]')
                sent.insert(e1start,'[E11]')
            else:
                sent.insert(e1end,'[E12]')
                sent.insert(e1start,'[E11]')
                sent.insert(e2end,'[E22]')
                sent.insert(e2start,'[E21]')
                
            wtest.writerow((sid,''.join(sent),re_type,sentID))
            #print(sid,''.join(sent),re_type,sentID)
            sid+=1
#             print(sentence_text[j],label[j])
    

    

['traffic_in', 'posess', 'sell_drugs_to', 'provide_shelter_for', 'NA']


In [45]:
import torch
from pytorch_transformers import BertTokenizer

In [46]:
feature=torch.load('data2/cached_dev_bert-base-uncased_400_semeval')

In [47]:
tokenizer = BertTokenizer.from_pretrained(
         "bert-base-chinese", do_lower_case=True)

In [54]:
tokenizer.convert_ids_to_tokens(feature[0].input_ids)

['[CLS]',
 '龙',
 '口',
 '市',
 '人',
 '民',
 '检',
 '察',
 '院',
 '起',
 '诉',
 '书',
 '指',
 '控',
 '，',
 '2014',
 '年',
 '11',
 '月',
 '至',
 '2015',
 '年',
 '1',
 '月',
 '期',
 '间',
 '，',
 '被',
 '告',
 '人',
 '[UNK]',
 '高',
 '某',
 '[UNK]',
 '先',
 '后',
 '多',
 '次',
 '容',
 '留',
 '吸',
 '毒',
 '人',
 '员',
 '[UNK]',
 '赵',
 '某',
 '某',
 '[UNK]',
 '、',
 '[UNK]',
 '汇',
 '峰',
 '[UNK]',
 '在',
 '其',
 '位',
 '于',
 '龙',
 '口',
 '市',
 '龙',
 '口',
 '经',
 '济',
 '开',
 '发',
 '区',
 '中',
 '国',
 '银',
 '行',
 '家',
 '属',
 '楼',
 '西',
 '单',
 '元',
 '4',
 '楼',
 '中',
 '户',
 '的',
 '住',
 '处',
 '吸',
 '食',
 '甲',
 '基',
 '苯',
 '丙',
 '胺',
 '（',
 '冰',
 '毒',
 '）',
 '。',
 '2015',
 '年',
 '1',
 '月',
 '8',
 '日',
 '，',
 '被',
 '告',
 '人',
 '高',
 '某',
 '被',
 '公',
 '安',
 '机',
 '关',
 '抓',
 '获',
 '归',
 '案',
 '。',
 '[SEP]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]'

In [55]:
import numpy as np

In [56]:

tokenizer.convert_ids_to_tokens(feature[0].input_ids*np.array(feature[0].e1_mask))

['[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[UNK]',
 '高',
 '某',
 '[UNK]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]',
 '[PAD]'

In [58]:
a

[100, 7770, 3378, 100]

In [63]:
tokenizer.convert_ids_to_tokens(np.array(a))

['[UNK]', '高', '某', '[UNK]']

In [62]:
type(feature[0].input_ids*np.array(feature[0].e1_mask))

numpy.ndarray

In [16]:
l=['qwrwe','wetert','er']

In [22]:
m = map(len,l)
m

m

In [31]:
import numpy as np
from sklearn.metrics import matthews_corrcoef, f1_score,precision_score,recall_score,accuracy_score
x=np.array([1,0,2,3,4,5])
y=np.array([1,1,0,1,1,5])
w=precision_score(y_true=x, y_pred=y, average='macro')
r=recall_score(y_true=x, y_pred=y, average='macro')
accuracy_score(y_true=x, y_pred=y)
print(w,r)

0.20833333333333334 0.3333333333333333


/home/chenyanguang/envs/anaconda3/envs/jointextraction/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [114]:
# import torch

x=torch.tensor([[[0,1,2]],

        [[1., 2.,3.]]])
y=torch.randn((3,1))

print(x,y)

a=torch.matmul(x,y).expand(-1, -1, 3)
print(a)
b=torch.matmul(x,y).expand(-1, -1, 3).transpose(1, 2)
print(b)
print(a+b)
torch.nn.functional.softmax(a+b,dim=2)

tensor([[[0., 1., 2.]],

        [[1., 2., 3.]]]) tensor([[ 0.8127],
        [-0.0581],
        [ 0.9994]])
tensor([[[1.9406, 1.9406, 1.9406]],

        [[3.6946, 3.6946, 3.6946]]])
tensor([[[1.9406],
         [1.9406],
         [1.9406]],

        [[3.6946],
         [3.6946],
         [3.6946]]])
tensor([[[3.8813, 3.8813, 3.8813],
         [3.8813, 3.8813, 3.8813],
         [3.8813, 3.8813, 3.8813]],

        [[7.3892, 7.3892, 7.3892],
         [7.3892, 7.3892, 7.3892],
         [7.3892, 7.3892, 7.3892]]])


tensor([[[0.3333, 0.3333, 0.3333],
         [0.3333, 0.3333, 0.3333],
         [0.3333, 0.3333, 0.3333]],

        [[0.3333, 0.3333, 0.3333],
         [0.3333, 0.3333, 0.3333],
         [0.3333, 0.3333, 0.3333]]])

In [14]:
a=set()
a.add(1)
a.add(2)
b=set()
b.add(2)
b.add(1)
b

{1, 2}

In [13]:
a


{1, 2}